import type { CatId, CatSkin } from './types';

export const CATS: readonly CatSkin[] = [
  {
    id: 'ginger',
    name: 'Рыжик',
    description: 'Рыжий полосатый, зелёные глаза',
    palette: { fur: '#F2A541', fur2: '#D47B1E', eye: '#5DBB63', nose: '#E8827A', innerEar: '#F6C9B8', pad: '#F4A6A0' },
    pawSymbol: '#paw-ginger',
    strike: 'swipe',
  },
  {
    id: 'coal',
    name: 'Уголёк',
    description: 'Чёрный, жёлтые глаза',
    palette: { fur: '#2B2B33', fur2: '#4A4A57', eye: '#F5C542', nose: '#1A1A1F', innerEar: '#6E5A66', pad: '#3A3A44' },
    pawSymbol: '#paw-coal',
    strike: 'jab',
  },
  {
    id: 'siam',
    name: 'Сима',
    description: 'Сиамская, голубые глаза',
    palette: { fur: '#F1E3C9', fur2: '#5B3A29', eye: '#6EC1E4', nose: '#5B3A29', innerEar: '#8B5E4A', pad: '#5B3A29' },
    pawSymbol: '#paw-siam',
    strike: 'slam',
  },
  {
    id: 'marine',
    name: 'Сержант',
    description: 'Космодесантник в силовой броне',
    palette: { fur: '#8C7B6B', fur2: '#5E514A', eye: '#FF8C1A', nose: '#4A3F38', innerEar: '#B59A88', pad: '#5E514A' },
    pawSymbol: '#paw-marine',
    strike: 'pump',
    accessory: 'helmet',
  },
  {
    id: 'wizard',
    name: 'Гарри',
    description: 'Юный волшебник в очках',
    palette: { fur: '#2E2A3A', fur2: '#4A4560', eye: '#4CAF50', nose: '#4A3F5C', innerEar: '#7A6E8C', pad: '#4A4560' },
    pawSymbol: '#paw-wizard',
    strike: 'spell',
    accessory: 'wizard',
  },
  {
    id: 'sherlock',
    name: 'Шерлок',
    description: 'Сыщик с Бейкер-стрит',
    palette: { fur: '#8A98A8', fur2: '#6B7886', eye: '#E8A33D', nose: '#5C5C66', innerEar: '#C7B1B6', pad: '#6B7886' },
    pawSymbol: '#paw-sherlock',
    strike: 'deduce',
    accessory: 'deerstalker',
  },
  {
    id: 'vanya',
    name: 'Ваня',
    description: 'Бежевый бородач с сигаретой',
    palette: { fur: '#C8A27A', fur2: '#8B5E3C', eye: '#7A9E3F', nose: '#B5745A', innerEar: '#E8C4A8', pad: '#B5745A' },
    pawSymbol: '#paw-vanya',
    strike: 'wave',
    accessory: 'beard',
  },
  {
    id: 'elman',
    name: 'Эльман',
    description: 'Гламурный дерзкий кот с бокалом брюта',
    palette: { fur: '#EDE4F5', fur2: '#8E44AD', eye: '#1ABC9C', nose: '#D81B8A', innerEar: '#F5C9E6', pad: '#8E44AD' },
    pawSymbol: '#paw-elman',
    strike: 'toast',
    accessory: 'shades',
  },
  {
    id: 'ksyusha',
    name: 'Ксюша',
    description: 'Нежная кошечка в золотых очках с плюшевым Ститчем',
    palette: { fur: '#FBEAEE', fur2: '#F4A7B9', eye: '#9B8FD9', nose: '#F28BA8', innerEar: '#F9C6D0', pad: '#F4A7B9' },
    pawSymbol: '#paw-ksyusha',
    strike: 'cuddle',
    accessory: 'roundgold',
  },
  {
    id: 'kama',
    name: 'Кама',
    description: 'Чёрная кошка-модель с кудрями и маникюром',
    palette: { fur: '#26222C', fur2: '#4B3F55', eye: '#E8C04B', nose: '#1A171C', innerEar: '#7A5C6E', pad: '#3A3340' },
    pawSymbol: '#paw-kama',
    strike: 'slash',
    accessory: 'curls',
  },
];

export function getCat(id: CatId): CatSkin {
  return CATS.find((c) => c.id === id) ?? CATS[0];
}
